svwizard/config/routes.rb
Rails.application.routes.draw do
  resources :conference_statuses

  resources :tickets

  resources :enrollments

  resources :enrollment_statuses

  resources :assignments

  resources :assignment_statuses

  devise_for :users
  resources :tasks

  resources :locations

  resources :conferences

  get 'welcome/index'

  root 'welcome#index'

end

svwizard/app/models/conference.rb
class Conference < ActiveRecord::Base
end

svwizard/app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :short_name, :year, :email, :volunteers, :volunteer_hours, :start_date, :end_date, :bid_day, :status, :maintenance)
    end
end

svwizard/app/helpers/conferences_helper.rb
module ConferencesHelper
end

svwizard/app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :volunteers %><br>
    <%= f.number_field :volunteers %>
  </div>
  <div class="field">
    <%= f.label :volunteer_hours %><br>
    <%= f.number_field :volunteer_hours %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :bid_day %><br>
    <%= f.number_field :bid_day %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :maintenance %><br>
    <%= f.check_box :maintenance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

svwizard/app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

svwizard/app/views/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short name</th>
      <th>Year</th>
      <th>Email</th>
      <th>Volunteers</th>
      <th>Volunteer hours</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Bid day</th>
      <th>Status</th>
      <th>Maintenance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.name %></td>
        <td><%= conference.short_name %></td>
        <td><%= conference.year %></td>
        <td><%= conference.email %></td>
        <td><%= conference.volunteers %></td>
        <td><%= conference.volunteer_hours %></td>
        <td><%= conference.start_date %></td>
        <td><%= conference.end_date %></td>
        <td><%= conference.bid_day %></td>
        <td><%= conference.status %></td>
        <td><%= conference.maintenance %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference', new_conference_path %>

svwizard/app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

svwizard/app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conference.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @conference.short_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @conference.year %>
</p>

<p>
  <strong>Email:</strong>
  <%= @conference.email %>
</p>

<p>
  <strong>Volunteers:</strong>
  <%= @conference.volunteers %>
</p>

<p>
  <strong>Volunteer hours:</strong>
  <%= @conference.volunteer_hours %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @conference.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @conference.end_date %>
</p>

<p>
  <strong>Bid day:</strong>
  <%= @conference.bid_day %>
</p>

<p>
  <strong>Status:</strong>
  <%= @conference.status %>
</p>

<p>
  <strong>Maintenance:</strong>
  <%= @conference.maintenance %>
</p>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>